// Bilingual content for Haifa's portfolio
const CONTENT = {
  en: {
    nav: { work: "Work", apps: "Apps", about: "About", contact: "Contact" },
    hero: {
      eyebrow: "iOS Developer — Suresnes, France",
      name: "Haifa Ben Letaifa",
      tagline: "8+ years shipping iOS apps at scale — from live sports broadcasting to a membership platform serving 120M users across 40+ countries.",
      sub: "Swift · SwiftUI · Modular SDK architecture. Currently shipping independent apps on the App Store.",
      cta: "Download CV",
      secondary: "Get in touch",
      available: "Open to senior iOS roles",
    },
    sections: {
      experience: "Experience",
      apps: "Independent Apps",
      openSource: "Open Source",
      skills: "Skills",
      about: "About",
      education: "Education",
      contact: "Contact",
    },
    about: {
      title: "About",
      body: [
        "I design and build iOS apps that ship — not prototypes. My work has reached tens of millions of users through France Télévisions' live sports coverage and Decathlon's global membership platform.",
        "On the side, I own three apps end-to-end on the App Store: concept, architecture, code, release. I work AI-augmented and lean on LLMs throughout the development cycle to move faster without cutting corners.",
      ],
    },
    experience: [
      {
        role: "iOS Developer",
        company: "SDK Squad · Decathlon",
        duration: "3 years",
        location: "Remote · France",
        bullets: [
          "Designed and built a SwiftUI modular SDK ecosystem (auth, membership, account) shared across multiple apps.",
          "Led accessibility compliance across all SDK UI components (VoiceOver, Dynamic Type).",
          "Set up Bitrise CI/CD pipelines; authored Swift-DocC documentation via GitHub Actions.",
          "Enforced quality via SPM, SwiftLint, and full unit test coverage across all modules.",
        ],
        impact: "SDKs shipped in Decathlon Coach & Decathlon Shopping — 120M+ users, 40+ countries.",
      },
      {
        role: "iOS Developer",
        company: "France Télévisions — france.tv sport",
        duration: "3 years",
        location: "France",
        bullets: [
          "Part of the team that rewrote the france.tv sport app from scratch in Swift/SwiftUI.",
          "Delivered real-time features for Tokyo 2020, Roland-Garros, and Dakar Rally.",
          "Integrated GDPR/ATT flows, Firebase, and Adjust; maintained Jenkins CI/CD pipelines.",
        ],
        impact: "Live sports coverage delivered to millions of users across France.",
      },
      {
        role: "iOS Developer",
        company: "Anypli",
        duration: "2 years",
        location: "France",
        bullets: [
          "Built and maintained multiple iOS apps in Swift across different client domains.",
          "Worked end-to-end with design, backend, and product teams.",
        ],
        impact: null,
      },
    ],
    apps: [
      {
        name: "Intimi",
        tagline: "Relationship companion",
        problem: "Couples lose track of the small things — dates, gestures, inside jokes. Intimi gives them a private, calm space to remember together.",
        role: "Full product ownership — concept, architecture, development, App Store release.",
        stack: ["SwiftUI", "SwiftData", "Custom UI"],
        accent: "#FF375F",
        url: "https://apps.apple.com/us/app/intimi/id6748307285",
        storeLabel: "View on App Store",
      },
      {
        name: "Pro Business",
        tagline: "Professional productivity",
        problem: "Solo professionals juggle clients, invoices, and follow-ups across too many tools. Pro Business keeps it in one focused iOS app with iCloud sync.",
        role: "Full product ownership — concept, architecture, development, App Store release.",
        stack: ["Swift", "Modular MVVM", "iCloud Sync"],
        accent: "#0A84FF",
        url: "https://apps.apple.com/us/app/pro-business/id6478776523",
        storeLabel: "View on App Store",
      },
      {
        name: "Qibla",
        tagline: "Offline prayer compass",
        problem: "Travelers and users without reliable data need an accurate prayer direction that works anywhere — no network, full accessibility.",
        role: "Full product ownership — concept, architecture, development, App Store release.",
        stack: ["CoreLocation", "Offline-first", "VoiceOver"],
        accent: "#30D158",
        url: "https://apps.apple.com/us/app/qibla-offline/id6744643047",
        storeLabel: "View on App Store",
      },
    ],
    openSource: {
      name: "OpenBridge",
      tagline: "Self-governing AI bridge for messaging channels",
      role: "Co-founder & Lead Developer.",
      problem: "Managing AI coding tools still lives inside the terminal. OpenBridge connects WhatsApp, Telegram, Discord and WebChat to a master AI that explores your workspace, spawns worker agents and executes tasks — using your existing subscriptions at zero extra cost.",
      stack: ["TypeScript", "Node.js 22+", "Multi-agent", "Claude · Codex · Gemini", "Apache-2.0"],
      highlights: [
        "Multi-AI orchestration across Claude, Codex and Gemini",
        "5 messaging channels — WhatsApp, Telegram, Discord, WebChat, Console",
        "Three access levels with phone whitelist",
        "Incremental workspace exploration on every commit",
      ],
      terminal: [
        { who: "you", text: "/ai run the tests and fix any failures" },
        { who: "ai", text: "On it…" },
        { who: "ai", text: "→ Reading test output… 45/47 passing" },
        { who: "ai", text: "→ Fixing 2 failures in auth.test.ts" },
        { who: "ai", text: "→ Re-running tests… 47/47 passing" },
        { who: "ai", text: "Changes committed. All tests pass." },
      ],
      url: "https://github.com/medomar/OpenBridge",
      urlLabel: "View on GitHub",
    },
    skillGroups: [
      { title: "Languages & UI", items: ["Swift", "SwiftUI", "UIKit"] },
      { title: "Concurrency", items: ["Async / Await", "Combine"] },
      { title: "Architecture", items: ["MVVM", "Clean Architecture", "SPM", "Modular SDKs"] },
      { title: "Quality", items: ["Unit Testing", "SwiftLint", "Swift-DocC"] },
      { title: "CI / CD", items: ["Bitrise", "GitHub Actions", "Jenkins"] },
      { title: "Accessibility", items: ["VoiceOver", "Dynamic Type"] },
      { title: "Analytics", items: ["Firebase", "Adjust"] },
      { title: "Workflow", items: ["AI-assisted development", "Vibe coding"] },
    ],
    education: {
      degree: "Engineering Degree in Computer Science",
      school: "École Nationale d'Ingénieurs de Sousse (ENISo)",
      location: "Tunisia",
    },
    contact: {
      title: "Let's talk",
      body: "Open to senior iOS roles. Based in Suresnes, France.",
      email: "haifabenletaifa@gmail.com",
      linkedin: "LinkedIn",
      linkedinHandle: "in/haifa-ben-letaifa",
    },
    footer: "Designed and built by Haifa Ben Letaifa · 2026",
  },
  fr: {
    nav: { work: "Expérience", apps: "Apps", about: "À propos", contact: "Contact" },
    hero: {
      eyebrow: "Développeuse iOS — Suresnes, France",
      name: "Haifa Ben Letaifa",
      tagline: "8+ ans à livrer des apps iOS à grande échelle — de la diffusion sportive en direct à une plateforme d'adhésion utilisée par 120M d'utilisateurs dans plus de 40 pays.",
      sub: "Swift · SwiftUI · Architecture SDK modulaire. Actuellement, je publie mes propres apps sur l'App Store.",
      cta: "Télécharger le CV",
      secondary: "Me contacter",
      available: "Ouverte aux postes iOS seniors",
    },
    sections: {
      experience: "Expérience",
      apps: "Apps indépendantes",
      openSource: "Open Source",
      skills: "Compétences",
      about: "À propos",
      education: "Formation",
      contact: "Contact",
    },
    about: {
      title: "À propos",
      body: [
        "Je conçois et développe des apps iOS qui sortent — pas des prototypes. Mon travail a touché des dizaines de millions d'utilisateurs via la couverture sportive en direct de France Télévisions et la plateforme d'adhésion mondiale de Decathlon.",
        "En parallèle, je possède trois apps de bout en bout sur l'App Store : concept, architecture, code, publication. Je travaille augmentée par l'IA et je m'appuie sur les LLM tout au long du cycle de développement pour aller plus vite sans rogner sur la qualité.",
      ],
    },
    experience: [
      {
        role: "Développeuse iOS",
        company: "SDK Squad · Decathlon",
        duration: "3 ans",
        location: "Remote · France",
        bullets: [
          "Conception et développement d'un écosystème SDK SwiftUI modulaire (auth, adhésion, compte) partagé entre plusieurs apps.",
          "Responsable de la conformité accessibilité sur tous les composants UI du SDK (VoiceOver, Dynamic Type).",
          "Mise en place des pipelines Bitrise CI/CD ; rédaction de la documentation Swift-DocC via GitHub Actions.",
          "Qualité garantie via SPM, SwiftLint et couverture complète des tests unitaires.",
        ],
        impact: "SDKs livrés dans Decathlon Coach & Decathlon Shopping — 120M+ utilisateurs, 40+ pays.",
      },
      {
        role: "Développeuse iOS",
        company: "France Télévisions — france.tv sport",
        duration: "3 ans",
        location: "France",
        bullets: [
          "Membre de l'équipe qui a réécrit l'app france.tv sport de zéro en Swift/SwiftUI.",
          "Livraison de fonctionnalités temps réel pour Tokyo 2020, Roland-Garros et le Dakar.",
          "Intégration des parcours RGPD/ATT, Firebase et Adjust ; maintenance des pipelines Jenkins CI/CD.",
        ],
        impact: "Couverture sportive en direct pour des millions d'utilisateurs en France.",
      },
      {
        role: "Développeuse iOS",
        company: "Anypli",
        duration: "2 ans",
        location: "France",
        bullets: [
          "Développement et maintenance de plusieurs apps iOS en Swift sur différents domaines clients.",
          "Travail bout en bout avec les équipes design, backend et produit.",
        ],
        impact: null,
      },
    ],
    apps: [
      {
        name: "Intimi",
        tagline: "Compagnon relationnel",
        problem: "Les couples perdent de vue les petites choses — dates, attentions, private jokes. Intimi leur offre un espace privé et apaisé pour s'en souvenir ensemble.",
        role: "Propriété produit complète — concept, architecture, développement, publication App Store.",
        stack: ["SwiftUI", "SwiftData", "UI personnalisée"],
        accent: "#FF375F",
        url: "https://apps.apple.com/us/app/intimi/id6748307285",
        storeLabel: "Voir sur l'App Store",
      },
      {
        name: "Pro Business",
        tagline: "Productivité professionnelle",
        problem: "Les indépendants jonglent entre clients, factures et relances sur trop d'outils. Pro Business centralise tout dans une app iOS focalisée avec sync iCloud.",
        role: "Propriété produit complète — concept, architecture, développement, publication App Store.",
        stack: ["Swift", "MVVM modulaire", "Sync iCloud"],
        accent: "#0A84FF",
        url: "https://apps.apple.com/us/app/pro-business/id6478776523",
        storeLabel: "Voir sur l'App Store",
      },
      {
        name: "Qibla",
        tagline: "Boussole de prière hors-ligne",
        problem: "Les voyageurs et utilisateurs sans connexion fiable ont besoin d'une direction de prière précise qui fonctionne partout — sans réseau, avec accessibilité complète.",
        role: "Propriété produit complète — concept, architecture, développement, publication App Store.",
        stack: ["CoreLocation", "Offline-first", "VoiceOver"],
        accent: "#30D158",
        url: "https://apps.apple.com/us/app/qibla-offline/id6744643047",
        storeLabel: "Voir sur l'App Store",
      },
    ],
    openSource: {
      name: "OpenBridge",
      tagline: "Pont IA auto-gouverné pour applications de messagerie",
      role: "Co-fondatrice & Lead Developer.",
      problem: "Gérer les outils IA de développement reste coincé dans le terminal. OpenBridge connecte WhatsApp, Telegram, Discord et WebChat à une IA maître qui explore votre workspace, lance des agents workers et exécute les tâches — en utilisant vos abonnements existants, sans coût supplémentaire.",
      stack: ["TypeScript", "Node.js 22+", "Multi-agent", "Claude · Codex · Gemini", "Apache-2.0"],
      highlights: [
        "Orchestration multi-IA : Claude, Codex et Gemini",
        "5 canaux de messagerie — WhatsApp, Telegram, Discord, WebChat, Console",
        "Trois niveaux d'accès avec whitelist téléphonique",
        "Exploration incrémentale du workspace à chaque commit",
      ],
      terminal: [
        { who: "you", text: "/ai lance les tests et corrige les échecs" },
        { who: "ai", text: "C'est parti…" },
        { who: "ai", text: "→ Lecture des tests… 45/47 passent" },
        { who: "ai", text: "→ Correction de 2 échecs dans auth.test.ts" },
        { who: "ai", text: "→ Re-run… 47/47 passent" },
        { who: "ai", text: "Changements committés. Tous les tests passent." },
      ],
      url: "https://github.com/medomar/OpenBridge",
      urlLabel: "Voir sur GitHub",
    },
    skillGroups: [
      { title: "Langages & UI", items: ["Swift", "SwiftUI", "UIKit"] },
      { title: "Concurrence", items: ["Async / Await", "Combine"] },
      { title: "Architecture", items: ["MVVM", "Clean Architecture", "SPM", "SDKs modulaires"] },
      { title: "Qualité", items: ["Tests unitaires", "SwiftLint", "Swift-DocC"] },
      { title: "CI / CD", items: ["Bitrise", "GitHub Actions", "Jenkins"] },
      { title: "Accessibilité", items: ["VoiceOver", "Dynamic Type"] },
      { title: "Analytics", items: ["Firebase", "Adjust"] },
      { title: "Workflow", items: ["Développement assisté par IA", "Vibe coding"] },
    ],
    education: {
      degree: "Diplôme d'ingénieur en informatique",
      school: "École Nationale d'Ingénieurs de Sousse (ENISo)",
      location: "Tunisie",
    },
    contact: {
      title: "Parlons",
      body: "Ouverte aux postes iOS seniors. Basée à Suresnes, France.",
      email: "haifabenletaifa@gmail.com",
      linkedin: "LinkedIn",
      linkedinHandle: "in/haifa-ben-letaifa",
    },
    footer: "Conçu et développé par Haifa Ben Letaifa · 2026",
  },
};

window.CONTENT = CONTENT;
